name: Deliverance
description: Universal document publishing system.
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up hydrun
      run: |
        curl -L -o /tmp/hydrun "https://github.com/pojntfx/hydrun/releases/latest/download/hydrun.linux-$(uname -m)"
        sudo install /tmp/hydrun /usr/local/bin
    - name: Build with hydrun
      run: hydrun -o danteev/texlive "apt update && apt install -y curl python3-pip tree && ./configure && make depend && make -j $(nproc)"
    - name: Fix permissions for output
      run: sudo chown -R $USER .
    - name: Publish release archive to GitHub releases
      if: ${{ github.ref == 'refs/heads/main' }}
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: latest
        prerelease: false
        files: |
          out/release.tar.gz
          out/release.zip
    - name: Extract release archive
      run: |
        mkdir -p /tmp/gh-pages
        tar xvzf out/release.tar.gz -C /tmp/gh-pages
    - name: Publish release to GitHub pages
      if: ${{ github.ref == 'refs/heads/main' }}
      uses: JamesIves/github-pages-deploy-action@4.1.0
      with:
        branch: gh-pages
        folder: /tmp/gh-pages
        git-config-name: GitHub Pages Bot
        git-config-email: bot@example.com
